name: gen_hs_explanations
channels:
  - conda-forge
dependencies:
  - python=3.8  # You can choose other versions as well
  - pip
  - pip:
    #- cudatoolkit  # Match this with your CUDA version if you are using a GPU
    - pandas
    - torch
    - torchvision
    - transformers
    - hydra-core
    - mlflow
    - sentencepiece
    - datasets
    - nltk
    - evaluate
    - rouge-score
    - bert-score
    - git+https://github.com/google-research/bleurt.git #bleurt-score
    - accelerate
    - bleu
