name: gen_hs_explanations
channels:
  - conda-forge
dependencies:
  - python=3.8  # You can choose other versions as well
  - pip
  - pip:
<<<<<<< HEAD
      - transformers
      - hydra-core
      - mlflow
      - sentencepiece
      - datasets
      - nltk
      - evaluate
      - rouge-score
      - accelerate
      - openai
      - pandas
      - torch
      - torchvision
      - bert-score
      - git+https://github.com/google-research/bleurt.git #bleurt-score
      - accelerate
      - bleu
