input:
  train_file: null
  dev_file: null
  uri_path: null
  run_name: ???
  experiment_name: RQ6
  experiment_description: "**RQ6:**  Can generation performance improve if we use finetuning"


model:
  params:
    pretrained_model_name_or_path: t5-base
    per_device_train_batch_size: 8,
    per_device_eval_batch_size: 8,
    eval_accumulation_steps: 1,
    learning_rate: 5e-4,
    weight_decay: 0.01,
    push_to_hub: True,
    logging_steps: 100,
    eval_steps: 1000,
    save_steps: 1000,
    save_total_limit: 2,
    num_train_epochs: 3,
    predict_with_generate: True,
    evaluation_strategy: "steps",